# Generated by Django 3.2.8 on 2021-10-09 09:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the asset owned', max_length=15)),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('price_at_buy', models.FloatField(help_text='Price at which each asset is bought', max_length=10)),
                ('currency_medium', models.CharField(help_text='Currency used to pay for the asset.', max_length=6)),
                ('currency_bought', models.CharField(help_text='The asset bought', max_length=7)),
                ('wallet_id', models.CharField(blank=True, max_length=30, null=True)),
                ('gas_price_paid', models.FloatField(blank=True, help_text='fees charged for asset bought', max_length=9, null=True)),
                ('date_bought', models.DateField(blank=True, help_text='The date when the asset was bought', null=True)),
                ('gains_losses', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(100)])),
                ('sold', models.BooleanField(verbose_name=False)),
                ('trade_hold', models.CharField(choices=[('TRADE', 'Trade'), ('HOLD', 'Hold')], default='HOLD', max_length=6)),
                ('date_added', models.DateTimeField(auto_now_add=True, help_text='date added to assetwatch')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asset',
                'verbose_name_plural': 'assets',
            },
        ),
    ]
